version: '3'

services:
  tracker:
    build:
      context: .
      dockerfile: Dockerfile
    image: tracker
    volumes:
    - .:/opt/app
    working_dir: /opt/app
    ports:
      - 8001:8001
    tty: true
    command: bash -c "python tracker/manage.py migrate && python tracker/manage.py runserver 0.0.0.0:8001"
  